# POST http://localhost:3001/persons/
# Content-Type: application/json

# {
#     "name": "hi2",
#     "number": "78"
# }

# DELETE http://localhost:3001/persons/3

# GET http://localhost:3001/persons/65fc4c2c36599f693391dcd4

# GET http://localhost:3001/persons/

PUT http://localhost:3001/persons/65fc4c2c36599f693391dcd4
Content-Type: application/json

{
    "name": "put",
    "number": "7878"
}